### ISSUE TITLE
First install crash

### ISSUE THREAD

**Issue by Indribell** [UniqueVision/plpgsql-lsp#10]
## Describe the bug

When the plugin is installed and no postgresql server information has been input. If you open a pgSQL file, this results in the (pgsql_check ) typechecker spewing a lot of ugly messages out and crashing the plugin as the plugin goes into a deathloop.

Entering the correct server information, will have no response from the plugin because "He's death Jim". Requiring a reload of the window/vsc. Then it will work properly.

I expect that wrong or changed database information will also result in the same crashing behavior.

## Expected Behavior

Working ;)

## Current Behavior

Crashes the plugin

## Steps to Reproduce

1. Install plugin
2. Open pgSQL file without server information in the settings
3. Past some code

## Environment

- [ x ] Windows
- [ ] Mac
- [ x ] Linux
- [ ] other (please specify)

**Comment by yas7010uv** [comment]
Thanks for the report.

Fixed and [v2.2.1](https://github.com/UniqueVision/plpgsql-lsp/tree/v2.2.1) is now available.
