### ISSUE TITLE
Query parameters enhancement

### ISSUE THREAD

**Issue by danicc097** [UniqueVision/plpgsql-lsp#12]
In light of #2 , I'd like to list the errors I've encountered so far for future reference:

To reproduce environment:

`docker run --name vscode-postgres -p 5777:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres:13
`

```SQL
create table users (
    id BIGSERIAL not null,
    username text not null,
    role text not null,
    primary KEY (id)
    );
```

`.vscode/settings.json`
```json
{
  "plpgsqlLanguageServer.database": "postgres",
  "plpgsqlLanguageServer.user": "postgres",
  "plpgsqlLanguageServer.password": "mysecretpassword",
  "plpgsqlLanguageServer.host": "localhost",
  "plpgsqlLanguageServer.port": 5777,
  "plpgsqlLanguageServer.defaultSchema": "public",
  "plpgsqlLanguageServer.definitionFiles": ["**/*.psql", "**/*.pgsql"],
  "plpgsqlLanguageServer.keywordQueryParameterPattern": "@{keyword}"
}

```

And individually paste the snippets below to reproduce errors:

1. **Syntax error: cannot insert multiple commands into a prepared statement**
Can't have multiple statements in a single file. Maybe this one is a bit tricky? Statements split by semicolon should be analyzed separately. Or alternatively split by user-defined regex, e.g. `-- name:` being quite common ( [aiosql](https://nackjicholson.github.io/aiosql/), [sqlc](https://github.com/kyleconroy/sqlc) )
```sql
 /* plpgsql-language-server:use-keyword-query-parameter */

-- name: GetUsersByRoles :many
select * from users where role = any(@roles::text[]);

-- name: GetUserById :many
select * from users where id = @id;
```

2. Parameter regex is matched in comments. Remove  `@` in `@roles` and it is gone. Errors vary depending on statement position, don't know if actually related:
**Syntax error: could not determine data type of parameter $1**
```sql
 /* plpgsql-language-server:use-keyword-query-parameter */

-- name: GetUsersByRoles :many
-- select * from users where role = any(@roles::text[]);

-- name: GetUserById :many
select * from users where id = @id;
```
**Syntax error: bind message supplies 2 parameters, but prepared statement "" requires 1**
```sql
 /* plpgsql-language-server:use-keyword-query-parameter */

-- name: GetUserById :many
select * from users where id = @id;

-- name: GetUsersByRoles :many
-- select * from users where role = any(@roles::text[]);
```

Apart from that, everything works beautifully so far. Even type annotations are correctly analyzed: 
```sql
select * from users where role = any(@roles::text); -- error: op ANY/ALL (array) requires array on right side
select * from users where role = any(@roles::int[]); -- error: operator does not exist: text = integer
```
Awesome job!

## Environment

Ubuntu 20.04
Extension [v2.2.0](https://github.com/UniqueVision/plpgsql-lsp/releases/tag/v2.2.0)

**Comment by yas7010uv** [comment]
Thanks for the detailed report!

Apparently, this issue is of more interest to SQL than PL/pgSQL.

This tool is intended for development around stored procedures/functions,
and there is a big difference in the usage of the our tool and the you mentioned tool.

We prefer simplicity of implementation, so avoid implementing feature to interpret comments and SQL syntax by ourself (we let it interpret comments in the first line only).

One feature we would like to support in this tool is auto-formatting, but we have not been able to implement it because we have not found a library that interprets PL/pgSQL stored procedure/function definitions and PostgreSQL comments (I really want auto-formatting feature!).

At this time we do not support the following

- Interpreting comments other than the first line of a file
- Interpreting multiple SQL queries with parameters in a file

This issue seems worth considering, but we do not intend to address the issue unless a better PL/pgSQL and PostgreSQL syntax parser library exists.

**Comment by a-mckinley** [comment]
FWIW, I am using the tool extensively with mixed SQL and plpgsql code, and finding it incredibly useful to help me build new features with realtime feedback for plpgsql-lsp!  It has really increased the speed of working on new PostgreSQL code,

I haven't yet hit the issues mentioned in this post, but I inevitably will as the new project grows.

**Comment by yassun4dev** [comment]
The purpose of this tool is to solve the problem of low performance when writing PostgreSQL code.
We are happy to hear reports of increased productivity from outside the company ;)

While several similar libraries exist ( [aiosql](https://nackjicholson.github.io/aiosql/), [sqlc](https://github.com/kyleconroy/sqlc) ), writing multiple statements with parameters in a single file is not standard practice.

How can I find a specific statement in the file? ... yes, by comments. 
However, the way comments are written depends on those library, and we can't support all libraries that we don't use.

To store 1 statement in 1 file would be one solution to this problem. 

Most of our company's projects are written in stored procedures (I don't want to talk about the good and bad of that approach here), and most of the use is to call a single query statement on the application side.

**Comment by yas7010uv** [comment]
The purpose of this tool is to solve the problem of low performance when writing PostgreSQL code.
We are happy to hear reports of increased productivity from outside the company ;)

While several similar libraries exist ( [aiosql](https://nackjicholson.github.io/aiosql/), [sqlc](https://github.com/kyleconroy/sqlc) ), writing multiple statements with parameters in a single file is not standard practice.

How can I find a specific statement in the file? ... yes, by comments.
However, the way comments are written depends on those library, and we can't support all libraries that we don't use.

To store 1 statement in 1 file would be one solution to this problem.

Most of our company's projects are written in stored procedures (I don't want to talk about the good and bad of that approach here), and most of the use is to call a single query statement on the application side.
