### ISSUE TITLE
trigger definitions break parsing

### ISSUE THREAD

**Issue by a-mckinley** [UniqueVision/plpgsql-lsp#42]
## Describe the bug

The following trigger definition breaks parsing

```sql
create table testing as select * from generate_series(1,5);

create or replace function test() returns trigger as
$$
begin
    return null;
end;
$$ language plpgsql;

drop trigger if exists test on testing;
create or replace trigger t after insert on testing
for each row
execute procedure test();
```

The error message is 

cannot parse. syntax error at or near "trigger"

## Environment

- [x] Linux

**Comment by yas7010uv** [comment]
@a-mckinley 

Sorry :(

This is [libpg-query](https://github.com/pyramation/libpg-query-node) problem.
This extension just returns the result from `libpg-query`.

**Comment by a-mckinley** [comment]
The problem seems to be they don't yet support PG14.

"create or replace trigger" is PG14 only.

**Comment by yas7010uv** [comment]
Thanks for your report!

We upgrade the version of npm packages in the next release (including 'libpg-query').
