### ISSUE TITLE
Server push?

### ISSUE THREAD

**Issue by Indribell** [UniqueVision/plpgsql-lsp#9]
### Is your enhancement related to a problem? Please describe.

A nice feature may be the ability to push the plpgsql content to the postgresql server [ as defined in the settings ]

### Describe the solution you would like

Example: F1 > Pgsql: Save function on server 

### Describe alternatives you have considered

Alternative: Save to server on file save? Risky ... i think the F1 where its a deliberate action is more safer.

**Comment by yas7010uv** [comment]
I have an idea, but I don't have time now.

I will work on it when I find the time.

**Comment by yassun4dev** [comment]
@Indribell 
Hi, we release v2.3.1, which will add the executeFileQuery command. In the [README.md](https://github.com/UniqueVision/plpgsql-lsp/tree/v2.3.1#execute-the-current-file-query) you can read how to execute the command.
